### ISSUE TITLE
Update to version 2.0

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/ec2-metadata#150]
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

This requires a new "knock" PUT request to get a session token before accessing any bits of data.

**Comment by ThrawnCA** [comment]
Can this also be backported to v1.8.0?

**Comment by adamchainz** [comment]
I won't backport since I only do Python 2 for money these days. But feel free to fork.

**Comment by ThrawnCA** [comment]
> I won't backport since I only do Python 2 for money these days. But feel free to fork.

Is there a way to make it compatible with both? The code didn't look drastically different between 1.8 and current.

**Comment by adamchainz** [comment]
The problem is that I manage [all 19 of my current OSS projects](https://adamj.eu/projects/) the same way. It takes extra effort to my general tooling and mental load to ensure things work on Python 2. Forking is not hard, you can [pip install from github](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) pretty easily.
