### ISSUE TITLE
Does instance-action support Spot?

### ISSUE THREAD

**Issue by jicowan** [adamchainz/ec2-metadata#201]
Will instance action get termination notifications from EC2 metadata?

**Comment by adamchainz** [comment]
I have no idea

The docs ( https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html ) say:

> Notifies the instance that it should reboot in preparation for bundling. Valid values: none | shutdown | bundle-pending. 

Not sure what "bundling" means.

**Comment by jicowan** [comment]
I’m not sure either. The path for spot is different. It’s /spot/instance-action. It responds with a 404 until the termination notification message is received.  I can’t test it because the spot termination simulator operates on a different IP:port, local host:1338. Do you think you could add a property for spot?

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by adamchainz** [comment]
Yes I could add a property but I've never set up a spot instance to check

If you could do that and make a PR (including tests, docs, and changelog note) I'd be happy to review and merge it.
