### ISSUE TITLE
Get tags from ec2 metadata

### ISSUE THREAD

**Issue by renanqts** [adamchainz/ec2-metadata#343]
### Description

After https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/
it is possible to get the tags from ec2 metadata.
Since I couldn't see how to do it with this library, I'm raising this issue.
It should be very useful for the use case of this library.

**Comment by adamchainz** [comment]
Done in #344
