### ISSUE TITLE
availability_zone_id may return 404

### ISSUE THREAD

**Issue by arossert** [adamchainz/ec2-metadata#349]
### Python Version

3.8.10

### Package Version

2.7.0

### Description

In some cases `ec2_metadata.availability_zone_id` returns 404
```
----> 1 ec2_metadata.availability_zone_id
File functools.py:967, in __get__(self, instance, owner)
File ec2_metadata/__init__.py:87, in availability_zone_id(self)
File ec2_metadata/__init__.py:65, in _get_url(self, url, allow_404)
File requests/models.py:960, in raise_for_status(self)
HTTPError: 404 Client Error: Not Found for url: http://169.254.169.254/latest/meta-data/placement/availability-zone-id
```
I assume that all that is needed is to use `allow_404` in `_get_url`

**Comment by adamchainz** [comment]
What kind of instances did you find it returns `None` for? govcloud or something weird like that?

And does `availablity_zone` still work?

[The docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html) don't say that `placement/availability-zone-id` is optional. Just:

> The static Availability Zone ID in which the instance is launched. The Availability Zone ID is consistent across accounts. However, it might be different from the Availability Zone, which can vary by account.

**Comment by arossert** [comment]
@adamchainz Thanks for looking into it, the `availablity_zone` is working but for some reason `availability_zone_id` returns 404.
```
In [1]: from ec2_metadata import ec2_metadata
In [2]: ec2_metadata.availability_zone
Out[2]: 'eu-west-1a'
```

What information do you need on the instance?

**Comment by adamchainz** [comment]
If there's no determinable reason why this returns 404, I would treat it as an EC2 bug. THere are no docs why. Please report to AWS support and get some information on why it returns 404, before we change the code.

**Comment by arossert** [comment]
I will try to contact AWS and see if this is indeed an issue or missing documentation.

**Comment by arossert** [comment]
I'm still waiting for AWS to respond but just noticed that the latest version added `ec2_metadata.tags`, by design this can raise 404, wouldn't it be better to return `None` or an empty set in this case?
