### ISSUE TITLE
Instance Role Name

### ISSUE THREAD

**Issue by levisbakalinsky** [adamchainz/ec2-metadata#36]
Would it be possible to return the role name from instance meta data? That way i don't have to make a boto3 call?

**Comment by adamchainz** [comment]
You don't need a call, you can parse it from the ARN that #37 adds. The ARN's look like `arn:aws:iam::123456789012:instance-profile/my-role-name` so you just need `arn.split('/')[1]`. You coudl add that as another attribute in #37.
