### ISSUE TITLE
HTTPConnectionPool(host='169.254.169.254') timeout in docker bridge mode

### ISSUE THREAD

**Issue by luuthang2011** [adamchainz/ec2-metadata#380]
### Python Version

3.9.13

### Package Version

2.10.0

### Description

I tried use ec2-metadata inside docker container with bridge mode. Curl "169.254.169.254" got ok but ec2-metadata raised error "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Read timed out. (read timeout=5.0)" 

![image](https://user-images.githubusercontent.com/13445565/182760279-32f12a71-f290-4133-a1fe-ac75ce18e6d6.png)

**Comment by adamchainz** [comment]
I need more information. I've never used a docker container with bridge mode. There shouldn't be anything fundamentally different between curl and python... Can you try using netcat, or opening a raw socket in python?

**Comment by luuthang2011** [comment]
I can connect to 169.254.169.254 with curl or netcat or python urllib.request from docker container in bridge mode. Ec2-metadata works well with --network host. 

![image](https://user-images.githubusercontent.com/13445565/182800785-8ff9102c-5878-4992-87fc-ef98218e64a9.png)

**Comment by adamchainz** [comment]
can you provide a way to recreate this? otherwise I can do no more.

**Comment by luuthang2011** [comment]
I can recreate the issue as follow: 
- Run a docker container on EC2 with default network config such as "docker run -it python bash"
- Install ec2-medata
- Try to get metadata using python 

![image](https://user-images.githubusercontent.com/13445565/183325762-38c4b0de-2d86-4817-b767-f228cfea44f4.png)

**Comment by Chitz** [comment]
I am facing the same issue. Any resolution/work around for this?

**Comment by luuthang2011** [comment]
I am getting metadata from ip 169.254.169.254 using requests. 

`ec2_metadata = requests.get('http://169.254.169.254/latest/dynamic/instance-identity/document').json()`

**Comment by adamchainz** [comment]
If `requests` works, this package should work, as it's only a thin layer around requests - see the code:

https://github.com/adamchainz/ec2-metadata/blob/70d1ecdae9a86acaeb8005d353e0cfc53ffdf628/src/ec2_metadata/__init__.py#L71-L77

**Comment by luuthang2011** [comment]
It should be but not

**Comment by zoltan-kecskemethy-epam** [comment]
To make this work you need to edit your instance IMDSv2 hop limit...

```bash
aws ec2 modify-instance-metadata-options  --instance-id <instanceId> --http-put-response-hop-limit 3 --http-endpoint enabled
```

References:

> [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)*, then the default hop limit for getting metadata is set to 1. This hop limit will prevent Docker containers from accessing the metadata (assuming they're using a Docker network, not the host network).

source: [Fetching AWS instance metadata from within Docker container?](https://stackoverflow.com/questions/22409367/fetching-aws-instance-metadata-from-within-docker-container)]

**Comment by adamchainz** [comment]
Great thanks @zoltan-kecskemethy-epam . Perhaps we could add a paragraph to the README.

**Comment by adamchainz** [comment]
I think this was covered by #405.
