### ISSUE TITLE
Publish package to conda-forge

### ISSUE THREAD

**Issue by dylanraws** [adamchainz/ec2-metadata#469]
### Description

Hi, I'm working on a project which requires dependencies to come from conda-forge. Could you publish this package there? The process is straight-forward, and in fact quite easy for packages hosted on pypi due to tools like grayskull.

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by adamchainz** [comment]
Sorry no I don’t have time to maintain that. I believe you can set it up to publish yourself.
