### ISSUE TITLE
is it possible to use ec2_metadata from lambda?

### ISSUE THREAD

**Issue by lots2learn** [adamchainz/ec2-metadata#59]
Hi Adam,

I stumbled on your code after having issues querying metadata in lambda. I'm always getting a 'connection refused' (both using requests to query the metadata directly and using your library). I can understand if it's a security issue AWS have put in place as with lambda you're using a shared tenancy, but i'm not sure. Do you know what the limitation is and do you know if and how this can be solved?

Thanks,
Marcel

**Comment by adamchainz** [comment]
Do lambda functions run on EC2? Probably but they'll never tell you
Would AWS let you access the metadata API from a lambda function if they did? *highly unlikely*

I doubt it can be 'solved', but the real question is: what were you trying to achieve?

**Comment by lots2learn** [comment]
Well, have to run somewhere so my guess is that it is in an ec2 instance, or as a container in an instance, but one that AWS controls.

I will be starting as an AWS trainer and wanted to create some functionality that allows students to quickly browse through the metadata tree and see what's in there. And the goal was to try and do this without using an ec2 instance with a website (i would have used PHP otherwise). I was just trying to figure out if i could use lambda for that. So, not a serious goal but just to explore what's in the art of the possible.

Thanks

**Comment by adamchainz** [comment]
Sounds nice. Maybe you could dump the metadata from a temporary instance into a file as a one-off and allow students to inspect that?

**Comment by lots2learn** [comment]
Thanks for the suggestion, but it the goal was to combine a couple of learnings and the metadata itself would just be a means to touch upon a couple of other things like lambda and possibly API Gateway as well. I think i'll create it using a php site now, running in an instance. That will definitely work but only serves showing what's in the metadata (and doing it on live data always goes down better than a 'canned' version :-).
