### ISSUE TITLE
Provide a test mock

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/ec2-metadata#84]
It would be useful to provide a test mock version of the `EC2Metadata` class that returns dummy data without making requests. This could also be provided as a pytest fixture so it's easy for pytest users to integrate it.

**Comment by seporaitis** [comment]
Just found out the hard way, that currently cached properties have to be cleared after each individual test, otherwise nasty stuff happens.

**Comment by adamchainz** [comment]
N.B. this might be easier with `requests-mock`, which the tests moved to in #97.

**Comment by pll** [comment]
Any update on providing a test mock for ec2_metadata?

Would love to have this functionality!

**Comment by adamchainz** [comment]
I think it may be a little more trouble than it's worth considering it really depends on the situation as to what data you'd get back. One can just use requests-mock as the test suite does.

**Comment by renanqts** [comment]
I guess that can help

https://github.com/aws/amazon-ec2-metadata-mock
